version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: quiz_builder_postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./supabase/migrations:/docker-entrypoint-initdb.d

  # Optional: Supabase local development
  # Uncomment if you want full Supabase local setup
  # supabase:
  #   image: supabase/supabase:latest
  #   ports:
  #     - "54321:8000"
  #   environment:
  #     POSTGRES_HOST: postgres
  #     POSTGRES_DB: postgres
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #   depends_on:
  #     - postgres

volumes:
  postgres_data: